### ISSUE TITLE
Testing Mode

### ISSUE THREAD

**Issue by remusache** [jamfprofessionalservices/DEP-Notify#1]
TESTING_MODE=true
The splash screen shows the stuff being installed, but they are not.

TESTING_MODE=false
As soon as the DEPNotify starts I get: COMPLETE_ALERT_TEXT="Your Mac is now finished with initial setup and configuration. Press Quit to get started!"

**Comment by kbareis** [comment]
Hey @remusache, can you attach three things for me, your modified shell script, DEP Notify config file ("/var/tmp/depnotify.log") and if running the newest version, the pre-config debug log ("/var/tmp/depNotifyDebug.log")

Thanks,
Kyle

**Comment by remusache** [comment]
@kbareis 
Hey Kyle!
Thank you for taking the time to look at my issue.
Attached you will find the files you requested. Except: /var/tmp/depNotifyDebug.log.

[Archive.zip](https://github.com/jamfprofessionalservices/DEP-Notify/files/2423130/Archive.zip)

**Comment by remusache** [comment]
Hey @kbareis, I made the modifications you mentioned.
Unfortunately, still no dice! The Progress bar goes thru all the POLICY_ARRAYs but it does not install the actual packages.
If I call a policy manually with the custom trigger it installs the package. So that means, that the Policies are OK.
When testing I always erase the Macintosh HD and install a fresh MacOS on the test machine.

[depNotify-Mod.sh.zip](https://github.com/jamfprofessionalservices/DEP-Notify/files/2424611/depNotify-Mod.sh.zip)

**Comment by kbareis** [comment]
@remusache I am glad to here that the script is going thru the whole `POLICY_ARRAY` now. When you are deploying the script via Jamf, do you have the `TESTING_MODE` variable set to `true` or `false`? If set to `true` the polices will not run and instead there is a `sleep 10` seconds command. If you flip `TESTING_MODE` to `false` then the script will execute the jamf policy commands.

**Comment by remusache** [comment]
Thank you @kbareis !
It works like a dream now.

You are going to hate me but I have another question/request… if I may…

Is there a chance you can do your script magic and invoke a window that allows the technician to name the computer, choose a city between Stockholm or Göteborg and then bind that computer to the Stockholm or Göteborg OU in AD.

Probably is a lot of work and the scope of the script is not to do that. But I had to ask… 😊 

Once again, thank you so much for your help and time.

**Comment by kbareis** [comment]
@remusache Awesome! Glad it's working for you now. As far as a window with drop downs, I am looking into the registration feature within DEP Notify. However, the biggest challenge is how to make it easy for folks to use. 

For example, if the registration page comes up and asks for computer name, then there is specific logic to make that happen that must be written. With the script as it stands now, much if it is very portable and doesn't have specific logic based on a particular workflow. If you are curious about trying it on your own, DEP Notify does have some info about the registration window on: https://gitlab.com/Mactroll/DEPNotify#registration-and-eula-windows

Additionally, you could do your workflow a different way. For example, you could have a policy change the computer name to the serial number of the device or something like that. Also, you could turn on authenticated DEP and scope the bind based on department or location pulled in by directory services. You could have two separate DEP PreStages, one for Stockholm and one for Götenborg. PreStages are something you can use for scoping policy content. Lastly, you could skip the bind all together and look at NoMAD, Apple Enterprise Connect, or Jamf Connect.

I will mark this issue as complete for now! Thanks @remusache
